---
name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
        fs-backend: [std, boost]
      fail-fast: false

    steps:
      - id: filesystem-backend
        env:
          FS_BACKEND: ${{ matrix.fs-backend }}
        run: echo "::set-output name=use-boost-filesystem::$([ $FS_BACKEND = 'boost' ] && echo 1 || echo 0)"
        shell: bash

      - uses: actions/checkout@v1
        with:
          submodules: true

      # WINDOWS
      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            REM We use this source (temporarily?) until choco has updated their version of conan
            choco source add -n=AFG -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
            choco install conan -y

            refreshenv
        shell: cmd

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            mkdir build
            cd build
            "C:\Program Files\Conan\conan\conan.exe" install .. -s build_type=Debug
            cmake -DUSE_BOOST_FILESYSTEM=${{ steps.filesystem-backend.outputs.use-boost-filesystem }} ..
            cmake --build .
        shell: cmd

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            dir
            cd build
            dir
            ".\bin\settings.exe"
        shell: cmd

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get -y install libboost-dev libboost-system-dev libboost-filesystem-dev rapidjson-dev

      - name: Install GCC 8.3 (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo add-apt-repository ppa:jonathonf/gcc && sudo apt-get update && sudo apt-get -y install gcc-8

      - name: Install dependencies (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: |
            brew install boost rapidjson
        shell: bash

      - name: Prepare GCC version (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
            echo "CC=/usr/bin/gcc-8" >> "$GITHUB_ENV"
            echo "CXX=/usr/bin/g++-8" >> "$GITHUB_ENV"
        shell: bash

      - name: Build (Ubuntu/MacOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
            mkdir build
            cd build
            cmake -DUSE_BOOST_FILESYSTEM=${{ steps.filesystem-backend.outputs.use-boost-filesystem }} ..
            make -j8
        shell: bash

      - name: Test (Ubuntu/MacOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
            cd build
            ./settings
        shell: bash
